# Generated by Django 4.2.1 on 2023-06-15 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("object", "0003_object_object_type"),
    ]

    operations = [
        migrations.RemoveField(model_name="object", name="object_type",),
        migrations.AddField(
            model_name="object",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="object",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="object",
            name="is_entity",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="object",
            name="is_key",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(name="Institution",),
    ]
