# Generated by Django 4.2.1 on 2023-07-11 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("faculty", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="faculty",
            options={"ordering": ["name"], "verbose_name_plural": "Faculties"},
        ),
    ]
