# Generated by Django 4.2.1 on 2023-07-11 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("department", "0002_department_faculty"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="slug",
            field=models.SlugField(default="none"),
        ),
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(max_length=120),
        ),
    ]
