# Generated by Django 4.2.1 on 2023-05-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0003_cell_i_cell_j_cell_value_alter_cell_column_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursecode",
            name="student_population",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="venue",
            name="capacity",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="cell",
            name="value",
            field=models.SmallIntegerField(
                choices=[(-1, -1), (0, 0), (1, 1)], default=0
            ),
        ),
    ]
