# Generated by Django 4.2.1 on 2023-06-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0010_alter_column_venue"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursecode",
            name="level",
            field=models.PositiveSmallIntegerField(
                choices=[(100, 100), (200, 200), (300, 300), (400, 400), (500, 500)],
                default=300,
            ),
            preserve_default=False,
        ),
    ]
