# Generated by Django 4.2.1 on 2023-06-20 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("department", "0001_initial"),
        ("schedule", "0011_coursecode_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursecode",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="department.department",
            ),
        ),
        migrations.AddField(
            model_name="supervisor",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supervisors",
                to="department.department",
            ),
        ),
        migrations.AddField(
            model_name="venue",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="venues",
                to="department.department",
            ),
        ),
    ]
