# Generated by Django 4.2.1 on 2023-06-21 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0012_coursecode_department_supervisor_department_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="supervisor", name="course",),
        migrations.AddField(
            model_name="coursecode",
            name="supervisor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courses",
                to="schedule.supervisor",
            ),
        ),
    ]
